"""
Quick GAN Comparison - Uses existing generated images
"""

from PIL import Image
import matplotlib.pyplot as plt
import numpy as np
import os
import glob

def create_quick_comparison():
    """Create quick comparison using existing generated images"""
    
    print("🎨 Creating GAN Real vs Fake Comparison")
    print("=" * 50)
    
    # Paths
    realwaste_base = r"C:\Users\Z-BOOK\OneDrive\Documents\DATASETS\realwaste\RealWaste"
    synthetic_dir = r"C:\Users\Z-BOOK\OneDrive\Documents\DATASETS\synthetic_outputs\large_batch_individual"
    
    # Load real images
    print("📸 Loading real waste images...")
    real_images = []
    
    # Get random real images from different categories
    categories = ['Plastic', 'Paper', 'Metal', 'Glass', 'Food Organics', 'Cardboard']
    
    for category in categories:
        cat_path = os.path.join(realwaste_base, category)
        if os.path.exists(cat_path):
            image_files = glob.glob(os.path.join(cat_path, '*.jpg')) + \
                         glob.glob(os.path.join(cat_path, '*.png'))
            
            if image_files:
                # Pick first image from category
                try:
                    img = Image.open(image_files[0]).convert('RGB')
                    img = img.resize((64, 64))
                    real_images.append(np.array(img))
                    if len(real_images) >= 8:
                        break
                except:
                    continue
    
    print(f"✅ Loaded {len(real_images)} real images")
    
    # Load synthetic images
    print("🤖 Loading GAN synthetic images...")
    synthetic_images = []
    
    if os.path.exists(synthetic_dir):
        synthetic_files = sorted(glob.glob(os.path.join(synthetic_dir, '*.png')))[:8]
        
        for syn_file in synthetic_files:
            try:
                img = Image.open(syn_file).convert('RGB')
                synthetic_images.append(np.array(img))
            except:
                continue
    
    print(f"✅ Loaded {len(synthetic_images)} synthetic images")
    
    # Create visualization
    print("📊 Creating comparison visualization...")
    
    num_images = min(len(real_images), len(synthetic_images), 8)
    
    # Create figure
    fig = plt.figure(figsize=(18, 6))
    
    # Title
    fig.suptitle('GAN Training Results: Real Waste Images vs Generated Synthetic Images',
                fontsize=18, fontweight='bold', y=0.98)
    
    # Top section label - Real images
    fig.text(0.02, 0.75, 'REAL\nIMAGES', 
            fontsize=14, fontweight='bold', color='darkgreen',
            ha='left', va='center',
            bbox=dict(boxstyle='round,pad=0.5', facecolor='lightgreen', alpha=0.7))
    
    # Plot real images (top row)
    for idx in range(num_images):
        ax = plt.subplot(2, num_images, idx + 1)
        ax.imshow(real_images[idx])
        ax.axis('off')
        
        # Add green border
        for spine in ax.spines.values():
            spine.set_edgecolor('green')
            spine.set_linewidth(3)
            spine.set_visible(True)
        
        # Add label for first image
        if idx == 0:
            ax.text(0.5, -0.15, 'From RealWaste Dataset', 
                   transform=ax.transAxes,
                   ha='center', fontsize=8, style='italic', color='green')
    
    # Bottom section label - Synthetic images
    fig.text(0.02, 0.25, 'GAN\nSYNTHETIC', 
            fontsize=14, fontweight='bold', color='darkblue',
            ha='left', va='center',
            bbox=dict(boxstyle='round,pad=0.5', facecolor='lightblue', alpha=0.7))
    
    # Plot synthetic images (bottom row)
    for idx in range(num_images):
        ax = plt.subplot(2, num_images, num_images + idx + 1)
        ax.imshow(synthetic_images[idx])
        ax.axis('off')
        
        # Add blue border
        for spine in ax.spines.values():
            spine.set_edgecolor('blue')
            spine.set_linewidth(3)
            spine.set_visible(True)
        
        # Add label for first image
        if idx == 0:
            ax.text(0.5, -0.15, 'Generated by WasteGAN', 
                   transform=ax.transAxes,
                   ha='center', fontsize=8, style='italic', color='blue')
    
    # Add detailed information box
    info_text = (
        f"Real Images (Top): Actual waste photos from RealWaste dataset | "
        f"Synthetic Images (Bottom): Generated by GAN trained on 4,769 real images for 30 epochs | "
        f"Image Size: 64×64 pixels RGB | "
        f"GAN Architecture: Generator/Discriminator with BCELoss optimization"
    )
    
    fig.text(0.5, 0.01, info_text,
            ha='center', va='bottom',
            fontsize=9, style='italic',
            bbox=dict(boxstyle='round,pad=0.7', facecolor='yellow', alpha=0.3, edgecolor='black'))
    
    plt.tight_layout(rect=[0.08, 0.04, 1, 0.96])
    
    # Save
    save_path = 'gan_real_vs_fake_comparison.png'
    plt.savefig(save_path, dpi=300, bbox_inches='tight', facecolor='white')
    plt.close()
    
    print(f"✅ Comparison saved: {save_path}")
    
    # Create detailed side-by-side comparison
    print("📊 Creating detailed side-by-side comparison...")
    
    fig, axes = plt.subplots(4, 2, figsize=(8, 14))
    
    for pair_idx in range(min(4, num_images)):
        # Real image (left)
        ax_real = axes[pair_idx, 0]
        ax_real.imshow(real_images[pair_idx])
        ax_real.axis('off')
        
        if pair_idx == 0:
            ax_real.set_title('REAL WASTE IMAGE', fontsize=12, fontweight='bold', 
                            color='green', pad=10)
        
        for spine in ax_real.spines.values():
            spine.set_edgecolor('green')
            spine.set_linewidth=4
            spine.set_visible(True)
        
        # Synthetic image (right)
        ax_fake = axes[pair_idx, 1]
        ax_fake.imshow(synthetic_images[pair_idx])
        ax_fake.axis('off')
        
        if pair_idx == 0:
            ax_fake.set_title('GAN SYNTHETIC IMAGE', fontsize=12, fontweight='bold',
                            color='blue', pad=10)
        
        for spine in ax_fake.spines.values():
            spine.set_edgecolor('blue')
            spine.set_linewidth(4)
            spine.set_visible(True)
        
        # Add pair number
        fig.text(0.02, 0.88 - (pair_idx * 0.22), f'Pair\n{pair_idx + 1}',
                fontsize=11, fontweight='bold', ha='center', va='center',
                bbox=dict(boxstyle='round', facecolor='lightgray', alpha=0.5))
    
    plt.suptitle('GAN Model: Side-by-Side Comparison of Real vs Synthetic Waste Images',
                fontsize=14, fontweight='bold', y=0.99)
    
    # Add explanation
    explanation = (
        "Left Column: Real waste images from dataset (actual photos)\n"
        "Right Column: GAN-generated synthetic images (AI-created)\n\n"
        "The GAN model learns patterns, textures, and features from real waste images\n"
        "and generates new synthetic images that can be used for data augmentation"
    )
    
    fig.text(0.5, 0.02, explanation,
            ha='center', va='bottom', fontsize=9,
            bbox=dict(boxstyle='round,pad=0.7', facecolor='wheat', alpha=0.5))
    
    plt.tight_layout(rect=[0.08, 0.06, 1, 0.98])
    
    save_path2 = 'gan_detailed_comparison.png'
    plt.savefig(save_path2, dpi=300, bbox_inches='tight', facecolor='white')
    plt.close()
    
    print(f"✅ Detailed comparison saved: {save_path2}")
    
    print(f"\n✅ All comparisons created!")
    print(f"\n📁 Generated files:")
    print(f"   1. gan_real_vs_fake_comparison.png (Grid view)")
    print(f"   2. gan_detailed_comparison.png (Side-by-side pairs)")
    
    print(f"\n💡 Key Observations:")
    print(f"   • GAN captures color distributions and textures from real data")
    print(f"   • Synthetic images show learned patterns and features")
    print(f"   • Useful for expanding training datasets")
    print(f"   • Can help address class imbalance issues")


if __name__ == "__main__":
    create_quick_comparison()
